name: XRNX Deploy (1 Folder -> 1 XRNX)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Zip the contents of the folder into an .xrnx file
      - name: Zip XRNX Package
        run: |
          zip -r kschzt.genq.xrnx kschzt.genq.xrnx/*
      
      # Dynamically generate a tag name
      - name: Generate Tag Name
        run: |
          echo "TAG_NAME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
      # Create a tag and push it
      - name: Create and Push Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Create GitHub release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
      
      # Upload .xrnx file
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kschzt.genq.xrnx
          asset_name: kschzt.genq.xrnx
          asset_content_type: application/octet-stream
