name: XRNX Deploy (1 Folder -> 1 XRNX)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Find and package all .xrnx directories
      - name: Find and Package XRNX Directories
        id: package_xrnx
        run: |
          mkdir -p packaged
          # Find all directories ending with .xrnx and package them
          find . -type d -name "*.xrnx" | while read -r xrnx_dir; do
            xrnx_name=$(basename "$xrnx_dir")
            zip -r "packaged/$xrnx_name" "$xrnx_dir"/*
          done
          # Save the list of packaged files for later steps
          ls -1 packaged/*.xrnx > packaged_files.txt

      # Generate a release tag based on the current date and time
      - name: Generate Tag Name
        run: |
          echo "TAG_NAME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Create and push a tag
      - name: Create and Push Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create a GitHub release for the tag
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      # Upload each packaged XRNX file to the release
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while read -r asset_path; do
            asset_name=$(basename "$asset_path")
            echo "Uploading $asset_name"
            curl \
              -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @"$asset_path" \
              "${{ steps.create_release.outputs.upload_url }}"?name="$asset_name"
          done < packaged_files.txt
